---
- name: Zsh
  hosts: localhost
  become: true
  tasks:
    - name: Ensure zsh installed
      ansible.builtin.package:
        name: zsh
        state: latest
        update_cache: true
    - name: Ensure zsh is the default shell
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: "/usr/bin/zsh"

- name: Mpv
  hosts: localhost
  become: true
  tasks:
    - name: Ensure mpv installed
      ansible.builtin.package:
        name: mpv
        state: latest

- name: Dotfiles
  hosts: localhost
  become: true
  tasks:
    - name: Stow dotfiles
      ansible.builtin.shell: stow --dotfiles */
