version = 3
final_space = true

[palette]
blue = '#8AADF4'
closer = 'p:os'
lavender = '#B7BDF8'
os = '#ACB0BE'
pink = '#F5BDE6'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = '{{.Icon}} '
foreground = 'p:os'
type = 'os'
style = 'plain'

[[blocks.segments]]
template = '{{ .Path }} '
foreground = 'p:blue'
type = 'path'
style = 'plain'

[blocks.segments.properties]
folder_icon = '....'
home_icon = '~'
style = 'agnoster_short'

[[blocks.segments]]
template = '{{ .HEAD }} '
foreground = 'p:lavender'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = false
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ''
foreground = 'p:closer'
type = 'status'
style = 'plain'

[blocks.segments.properties]
always_enabled = true
