# --- Window Rules ---
windowrulev2 = float, class:firefox, title:^Picture-in-Picture$
windowrulev2 = float, class:steam, title:^notificationtoasts
windowrulev2 = move 100%-8 100%-8, class:steam, title:^notificationtoasts
windowrulev2 = suppressevent maximize, class:.*

# Wezterm workaround from niri config
windowrulev2 = tile, class:^org\.wezfurlong\.wezterm$

# DMS Specific Rules
layerrule = blur, dms:blurwallpaper
layerrule = ignorealpha 0.5, dms:blurwallpaper
